maven_home_parent_directory: /usr/lib/apache-maven
maven_file_name: apache-maven-{{ maven_version }}-bin.tar.gz
maven_download_url: 'https://dlcdn.apache.org/maven/maven-{{ maven_version[:1] }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz'
