---
- name: Ensure system is set up to work with https sources
  ansible.builtin.package:
    name: apt-transport-https, ca-certificates, curl
    state: present

- name: Install the apt GPG key
  ansible.builtin.get_url:
    url: 'https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key'
    dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc
    mode: '0644'

- name: Set up the repository for kubernetes
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /'
    state: present
    filename: kubernetes
    update_cache: true
