---
- name: Ensure the necessary packages are present
  package:
    name: apt-transport-https, gnupg
    state: present

- name: Download the Eclipse Adoptium GPG key
  ansible.builtin.apt_key:
    url: 'https://packages.adoptium.net/artifactory/api/gpg/key/public'
    keyring: /usr/share/keyrings/adoptium-keyring.gpg
    state: present

- name: Configure the Eclipse Adoptium apt repository
  ansible.builtin.apt_repository:
    repo: 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/adoptium-keyring.gpg] https://packages.adoptium.net/artifactory/deb {{ ansible_distribution_release }} main'
    state: present
    filename: adoptium
    update_cache: true
