---
- name: Update 'java' alternatives
  community.general.alternatives:
    name: java
    link: /usr/bin/java
    path: '/usr/lib/jvm/temurin-{{ java_version }}-jdk/bin/java'

- name: Update 'javac' alternatives
  community.general.alternatives:
    name: javac
    link: /usr/bin/javac
    path: '/usr/lib/jvm/temurin-{{ java_version }}-jdk/bin/javac'
