---
- name: Register architecture variable
  ansible.builtin.shell: dpkg --print-architecture
  register: adoptium_architecture
  ignore_errors: true

- name: Update 'java' alternatives
  alternatives:
    name: java
    link: /usr/bin/java
    path: '/usr/lib/jvm/temurin-{{ java_version }}-jdk-{{ adoptium_architecture.stdout }}/bin/java'

- name: Update 'javac' alternatives
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: '/usr/lib/jvm/temurin-{{ java_version }}-jdk-{{ adoptium_architecture.stdout }}/bin/javac'
