---
- name: Install packages to allow apt to use a repository over HTTPS
  package:
    name: ca-certificates, curl, gnupg
    state: present

- name: Add Azul GPG key
  apt_key:
    url: 'https://www.azul.com/wp-content/uploads/2021/05/0xB1998361219BD9C9.txt'
    keyring: /usr/share/keyrings/azul-keyring.gpg
    state: present

- name: Set up the repository for Azul
  apt_repository:
    repo: 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/azul-keyring.gpg] https://repos.azul.com/zulu/deb/ stable main'
    state: present
    filename: azul-zulu
    update_cache: true
