---
- name: Install Required packages
  ansible.builtin.package:
    name:
      - python3
    state: present

- name: Create a temporary directory to download the AWS CLI bundle
  ansible.builtin.file:
    path: /tmp/awscli
    state: directory
    mode: '0755'

- name: Download and unpack the AWS CLI distribution bundle
  ansible.builtin.unarchive:
    src: 'https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip'
    dest: /tmp/awscli/
    remote_src: true

- name: Install AWS CLI
  ansible.builtin.shell: /tmp/awscli/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

- name: Create the local .aws directory
  ansible.builtin.file:
    path: '/home/{{ ansible_user }}/.aws'
    state: directory
    mode: '0755'
  become: false

- name: Install the Session Manager plugin
  apt:
    deb: 'https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb'

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/awscli
    state: absent
